add extra_slots metamodel slot
linkml/linkml-model pull request #205
Opened 2024-09-26 05:37 UTC by sneakers-the-rat

Related to:
- proposal: https://github.com/linkml/linkml/issues/2241
- https://github.com/linkml/linkml/issues/2238
- https://github.com/linkml/linkml/issues/1404

Many modeling frameworks allow one to specify how to handle extra values provided to an instance of a class. By default linkml forbids all additional data in those frameworks that allow that. In addition to declaring whether or not extra data is allowed, it would also be nice to constrain what type that extra data can be. There are no other existing linkml metamodel items that could be used for this that i am aware of, but please let me know if we can repurpose something existing here.

The two major points of ambiguity that i can see
- interpreting this as defining constraints on extra slots defined in child classes (seems relatively low likelihood, but possible). Added a note in the description for this property to head that off
- interpreting some properties of an anonymous slot expression as being about the requiredness or cardinality of extra slots (seems more likely). eg. one might think they could set `maximum_cardinality` to limit the number of extra slots that could be provided, or make providing extra slots `required`. Added examples to clarify these behaviors - I am not sure if there is a circumstance where we would want to support that, but if we did then we could turn this into a class so someone could specify something like this, which would be backwards compatible with any `anonymous_slot_expression` definitions that happen in the meantime:
```yaml
extra_slots:
  extra_params:
    maximum_cardinality: 5
  # the rest of the anonymous slot expression..
  range: string
  multivalued: true
  maximum_cardinality: 3
```

to mean "there can be at most 5 extra slots that are lists of strings at most length 3"

the examples in the PR and the prior issue give examples of expected use, but for the sake of recordkeeping:

Allow all extra slots:
```yaml
MyClass:
  extra_slots: true
```

Allow no extra slots (default):
```yaml
MyClass:
  extra_slots: false
```

Allow all extra slots (if someone defines `extra_slots` as an explicit null, i actually think this shouldn't be allowed to reduce implementation burden, but hey):
```yaml
MyClass:
  extra_slots: 
```

Allow extra slots if they are strings
```yaml
MyClass:
  extra_slots:
    range: string
```

Allow extra slots if they are strings or integers
```yaml
MyClass:
  extra_slots:
    any_of:
      - range: string
      - range: integer
```

Allow extra slots if they are instances of the class `SecondClass`
```yaml
MyClass:
  extra_slots:
    any_of:
      - range: SecondClass
```

This is high priority for me since it's blocking final implementation of nwb-linkml, so if we can make relatively short work of this then i'll implement it for pydanticgen, pythongen, and json schema gen as thanks for the quickness.

2024-09-26 06:20 UTC, sneakers-the-rat commented
i am told that there is prior art here? https://mapping-commons.github.io/sssom/spec-model/

2024-09-26 14:39 UTC, turbomam commented
This makes me nervous but I agree 100% that many users want it, and if we are going to allow it, this seems like a step in the right direction.

I never would have thought of specifying the maximum cardinality of extra slots, but I suppose it wouldn't hurt. I would be interested in seeing some examples of the limit solving a problem.

I'm also interested to hear how SSSOM provides a solution for this that LinkML could follow.

@sneakers-the-rat do you think your implementation could limit extra slots to scalar key/value pairs? Maybe constraining the range to string would do that, in the sense that the extra slot's value could never be an instance of some class.

2024-09-26 14:53 UTC, sierra-moxon commented
Are `5` and `3` swapped in your example `maximum_cardinality` slots?

2024-09-26 15:01 UTC, sierra-moxon commented
Also - how does it play with the `closed` metamodel component?

2024-09-26 19:59 UTC, sneakers-the-rat commented
> This makes me nervous but I agree 100% that many users want it

I get it. I often find myself of several minds working on linkml, and there's this recurring 3-way tension between how we think schemas *should* be modeled, what is *possible to express," and what is *feasible to implement.* I think allowing arbitrary extra items probably scores low on the "should" scale (why not add those things to the model), though not always true for eg. property-centric frameworks, but very high on the "expressiveness" scale, and relatively high on the implementability scale for those frameworks where it's possible. In this case i'm modeling a schema/format/standard for whom constraints on arbitrary extra fields are a core part of the format. I personally would have probably designed it differently, but it exists and it would be nice to be able to express it.

> SSSOM

Don't know it, but yes as always let's integrate with prior art if possible. I am partly making this PR to try and get the ball rolling on this rather than trying to say "this is definitely what we should do and i have considered all options" because the other issues without a PR on the table were languishing.

> do you think your implementation could limit extra slots to scalar key/value pairs? Maybe constraining the range to string would do that, in the sense that the extra slot's value could never be an instance of some class.

I think that allowing the slot range is relatively important, and if we don't add it we'll want to do so later. the two examples i was giving in the prior issue were JSON Schema and Pydantic, both of which allow you to set what would be partial/anonymous slot schemas in linkml for extra properties. specifically allowing class ranges in `extra` is important because you might want to say "any additional properties must be some instance of this class *or any of its subclasses*" where you can't naturally anticipate what each of those subclasses might be, but you can specify some general abstract form in a parent class. This would also be important to be able to do in pattern-based or structurally typed frameworks. 

the version in this PR doesn't get us all the way into abstractionland (eg. one can't set a pattern constraint on what additional fields `name` could be, i don't think), but does allow us the expressiveness to generate into those frameworks.

> Are 5 and 3 swapped in your example maximum_cardinality slots?

haha yes see this is the exact ambiguity i'm talking about. The `AnonymousSlotExpression` would be defining the pattern to validate **each** additional property present in the data, rather than **all** additional properties. 

So by itself, 

```yaml
MyClass:
  extra_slots:
    range: string
    multivalued: true
    maximum_cardinality: 3
```

would behave like

```yaml
MyClass:
  attributes:
    extra_1:
      range: string
      multivalued: true
      maximum_cardinality: 3
    extra_2:
      range: string
      multivalued: true
      maximum_cardinality: 3
    # ...
```

which is why i added [this](https://github.com/linkml/linkml-model/pull/205/files#diff-5fc807b5f16aafb921180aea704aa97a4c5a869eeff86344975963ba6b0bb49dR1388-R1394) example to clarify that explicitly. 

The other way would be mixing levels, where it would become ambiguous whether we were talking about *all* or *each* - eg if `multivalued: false`, does that mean we can only have one additional property in the data? if we were to do something like an `extra_params` to parameterize *all* extras, then i think we would want to make a separate class with a specific set of metamodel slots to support like `*_cardinality`, etc. because reusing `anonymous_slot_expression` would make for too many metamodel slots that would be meaningless/ambiguous in that context.

> Also - how does it play with the `closed` metamodel component?

i'm not finding this, can you link me to the definition?

2024-09-27 20:07 UTC, sierra-moxon commented
I got it from the linked issue - https://github.com/linkml/linkml/issues/1404 looks like it's a flag to a specific generator.  but my question still is bugging me a bit - do we have to consider that flag and how it behaves with this change?

2024-09-27 20:30 UTC, cmungall requested changes

2024-09-27 20:40 UTC, sierra-moxon commented
from LinkML dev call - @sneakers-the-rat - would you mind coming next week to discuss at our next dev call?  (or we can schedule a one-off if this is urgent).

2024-09-27 20:49 UTC, sneakers-the-rat commented
I would think that flag gets deprecated in favor of specifying it in the schema, with ample transition time where it basically behaves like `extra_slots=True/False` in the meantime? Seems like if we make it a property in a schema we should take out generator-conditional behavior. Maybe we also want to add this as a schema-level property as well if someone wants to set it for all classes at once? I could implement that in schemaview if we want.

2024-09-27 21:42 UTC, sneakers-the-rat commented
Had a few minutes before needing to run, but updated OP with a class slot option that avoids `any_of` in the metamodel. I'll come back and add json schema and pydantic examples later

2024-09-27 21:44 UTC, sneakers-the-rat commented on linkml_model/model/schema/meta.yaml
> +      - range: boolean
updated OP with another possible example that avoids this :)

2024-09-28 02:11 UTC, cmungall commented
I favor the 2nd option. It also makes it easier for frameworks to declaratively declare their conformance profile (e.g. json-schema can declare it supports `extra_slots.allowed` but not `extra_slots.slot_expression`.

If you like we can proceed with `extra_slots.allowed` in its own PR if it's easier to chunk this up. It should be uncontroversial both in terms of utility-vs-complexity and its semantics (as is evidenced by presence in both json-schema and pydantic). In fact we are scheduled for a new release soon so this part could easily go in.

For constraining the expression part, I would like to make sure we are future proofing for future changes. See my comments here https://github.com/linkml/linkml/issues/2241#issuecomment-2380345076 on the common use case of allowing additional slots if their names match certain patterns. I am not sure how obscure a use case this is (or how obscure the ability to semi-constrain additional slots is). It would be good to compile examples outside of NWB/HDMF where this is allowed.

We also need to decide on inheritance semantics. What if I want to declare at a base class level that any extra slots should be integers, but I will leave it to subclasses to decide whether this is switched on? I think it's easier to permit this kind of behavior than forbid it. The semantics here should be monotonic, i.e you can progressively constrain not relax.

2024-09-28 03:33 UTC, sneakers-the-rat commented
> the common use case of allowing additional slots if their names match certain patterns

This is related to the "level shifting" problem discussed above re: whether `max_cardinality` refers to *each* of the additional slots implied by the data or *all* of the slots: I.e. whether it means "each extra slot can have max cardinality 5" or "there can be maximum 5 additional slots." Splitting up the extra expression allows for this subtlety to be resolved naturally, by adding an additional slot that conditions patterns like what the extra slots can be named, their cardinality, etc. Separate from declaring conditions for the provided slots themselves 

> What if I want to declare at a base class level that any extra slots should be integers, but I will leave it to subclasses to decide whether this is switched on? I think it's easier to permit this kind of behavior than forbid it. The semantics here should be monotonic, i.e you can progressively constrain not relax.

This is related to the previous discussion in #2241 on the difference between specifying addition slots *provided by the data* and additional slots *defined in inheriting classes*. Re: monotonicity, since there isn't a general way this is enforced/declared in the metamodel or schemaview, I would think that it would take on the same conventional status as the rest of linkml: it is currently technically possible to override parent class declarations for all but min/max value last I checked, but the conventional expectation is monotonicity.

2024-10-01 04:30 UTC, sneakers-the-rat commented
Updated OP with examples in JSON schema and pydantic

2024-10-01 18:58 UTC, cmungall commented
Just a general note: we have been discussing this proposal in relation to pydantic and json-schema, but shacl has an analogous mechanism `sh:closed`.

See https://www.w3.org/TR/shacl/#ClosedConstraintComponent

(I don't know if we also want to have something like shacl's ignore here too)

2024-10-01 20:20 UTC, sneakers-the-rat commented
Is there a way to express constraints for extra unspecified properties as well? Or would that just be adding a union onto the general property constraint? I see the ignoredProperties constraint, but that looks like it's just limiting to a (list of) URIs for slots/props

2024-10-04 16:57 UTC, sierra-moxon commented
@sneakers-the-rat - thank you very much for the addition doc here!  Option 2 is terrific - and now I understand it! :D

2024-10-21 22:02 UTC, sneakers-the-rat commented
OK i have updated the impl here to be the class slot. I reused `range_expression` since it was the only slot i could find with a matching `range`, and it feels like an appropriate usage, semantically. 

How does this look?

2024-10-21 22:58 UTC, cmungall approved these changes

2024-10-21 22:59 UTC, merged